run-server:
	mise r run-server

run-client:
	mise r run-client

setup-auth:
	mise r setup-auth

run-server-auth:
	mise r run-server-auth

run-server-auth-tls:
	mise r run-server-auth-tls

run-server-auth-internal:
	mise r run-server-auth-internal

run-server-auth-external:
	mise r run-server-auth-external

run-server-auth-with-access-token:
	mise r run-server-auth-with-access-token

run-server-auth-with-external-access-token:
	mise r run-server-auth-with-external-access-token

run-server-auth-internal-as-external:
	mise r run-server-auth-internal-as-external

run-client-auth:
	mise r run-client-auth

run-client-auth-tls:
	mise r run-client-auth-tls

run-client-auth-external:
	mise r run-client-auth-external

run-client-auth-external-direct:
	mise r run-client-auth-external-direct

