[vars]
repo_root = "{{ [config_root, '../../../'] | join_path | canonicalize }}"

[tasks.run-server]
description = "WAT"
run = "go run server/cmd/main.go -instance-name=echo-server"

[tasks.run-client]
run = "go run client/main.go -host=echo-server"

[tasks.setup-auth]
# These are inherited from the mise.toml file in the root of the repo.
depends = ["setup-cert", "setup-priv-key"]

[tasks.run-server-auth]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server -api-key=supersecretkeyohmy \
  -auth-private-key={{vars.repo_root}}/etc/test_keys/pkcs8.key \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem
"""

[tasks.run-server-auth-tls]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server \
  -auth-private-key={{vars.repo_root}}/etc/test_keys/pkcs8.key \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem \
  -tls-auth
"""

[tasks.run-server-auth-internal]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server -api-key=supersecretkeyohmy \
  -auth-public-key={{vars.repo_root}}/etc/test_keys/public-key.pem \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem \
  -external-auth-addr=https://localhost:8081
"""

[tasks.run-server-auth-external]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server -api-key=supersecretkeyohmy \
  -auth-public-key={{vars.repo_root}}/etc/test_keys/public-key.pem \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem \
  -external-auth-addr=https://localhost:8081
"""

[tasks.run-server-auth-with-access-token]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server-external -api-key=supersecretkeyohmy \
  -auth-private-key={{vars.repo_root}}/etc/test_keys/pkcs8.key \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem \
  -use-access-token
"""

[tasks.run-server-auth-with-external-access-token]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server-external -api-key=supersecretkeyohmy \
  -auth-private-key={{vars.repo_root}}/etc/test_keys/pkcs8.key \
  -auth-public-key={{vars.repo_root}}/etc/test_keys/public-key.pem \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem \
  -use-access-token \
  -external-auth-addr=https://localhost:8081 \
  -external-auth 8081
"""

[tasks.run-server-auth-internal-as-external]
depends = ["setup-auth"]
run = """\
go run server/cmd/main.go -instance-name=echo-server -api-key=supersecretkeyohmy \
  -auth-public-key={{vars.repo_root}}/etc/test_keys/public-key.pem \
  -auth-private-key={{vars.repo_root}}/etc/test_keys/pkcs8.key \
  -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem \
  -external-auth-addr=https://localhost:8081 \
  -external-auth
"""

[tasks.run-client-auth]
depends = ["setup-auth"]
run = "go run client/main.go -host=echo-server -api-key=supersecretkeyohmy"

[tasks.run-client-auth-tls]
depends = ["setup-auth"]
run = """\
go run client/main.go -host=echo-server -tls-cert={{vars.repo_root}}/etc/test_keys/localhost/cert.pem \
  -tls-key={{vars.repo_root}}/etc/test_keys/localhost/key.pem
"""

[tasks.run-client-auth-external]
depends = ["setup-auth"]
run = "go run client/main.go -host=echo-server -api-key=supersecretkeyohmy -external-auth-addr=localhost:8081"

[tasks.run-client-auth-external-direct]
depends = ["setup-auth"]
run = "go run client/main.go -api-key=supersecretkeyohmy -external-auth-addr=localhost:8081 -host=localhost:8080"
