// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SignalingServiceClient is the client API for SignalingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SignalingServiceClient interface {
	// Call makes an offer to a client that it expects an answer to. The host
	// of the client in question should be identified in the rpc-host metadata
	// field.
	// Note: Based on how this is a server streaming responnse to the caller,
	// we do not have a good way of knowing if the caller has disappeared.
	// Depending on answerer timeouts and concurrency limits, this can result in
	// hangs on the answerer waiting for a connection to establish, which in turn
	// can result in the caller waiting for an answerer to be listening.
	Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (SignalingService_CallClient, error)
	// CallUpdate is used to send additional info in relation to a Call.
	// The host of the client for the call in question should be identified
	// in the rpc-host metadata field.
	// In a world where https://github.com/grpc/grpc-web/issues/24 is fixed,
	// this should be removed in favor of a bidirectional stream on Call.
	CallUpdate(ctx context.Context, in *CallUpdateRequest, opts ...grpc.CallOption) (*CallUpdateResponse, error)
	// Answer sets up an answering service where the caller answers call offers
	// and responds with answers.
	// The host(s) to answer for should be in the rpc-host metadata field.
	Answer(ctx context.Context, opts ...grpc.CallOption) (SignalingService_AnswerClient, error)
	// OptionalWebRTCConfig returns any WebRTC configuration the caller may want to use.
	// The host to get a config for must be in the rpc-host metadata field.
	OptionalWebRTCConfig(ctx context.Context, in *OptionalWebRTCConfigRequest, opts ...grpc.CallOption) (*OptionalWebRTCConfigResponse, error)
}

type signalingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSignalingServiceClient(cc grpc.ClientConnInterface) SignalingServiceClient {
	return &signalingServiceClient{cc}
}

func (c *signalingServiceClient) Call(ctx context.Context, in *CallRequest, opts ...grpc.CallOption) (SignalingService_CallClient, error) {
	stream, err := c.cc.NewStream(ctx, &SignalingService_ServiceDesc.Streams[0], "/proto.rpc.webrtc.v1.SignalingService/Call", opts...)
	if err != nil {
		return nil, err
	}
	x := &signalingServiceCallClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SignalingService_CallClient interface {
	Recv() (*CallResponse, error)
	grpc.ClientStream
}

type signalingServiceCallClient struct {
	grpc.ClientStream
}

func (x *signalingServiceCallClient) Recv() (*CallResponse, error) {
	m := new(CallResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *signalingServiceClient) CallUpdate(ctx context.Context, in *CallUpdateRequest, opts ...grpc.CallOption) (*CallUpdateResponse, error) {
	out := new(CallUpdateResponse)
	err := c.cc.Invoke(ctx, "/proto.rpc.webrtc.v1.SignalingService/CallUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *signalingServiceClient) Answer(ctx context.Context, opts ...grpc.CallOption) (SignalingService_AnswerClient, error) {
	stream, err := c.cc.NewStream(ctx, &SignalingService_ServiceDesc.Streams[1], "/proto.rpc.webrtc.v1.SignalingService/Answer", opts...)
	if err != nil {
		return nil, err
	}
	x := &signalingServiceAnswerClient{stream}
	return x, nil
}

type SignalingService_AnswerClient interface {
	Send(*AnswerResponse) error
	Recv() (*AnswerRequest, error)
	grpc.ClientStream
}

type signalingServiceAnswerClient struct {
	grpc.ClientStream
}

func (x *signalingServiceAnswerClient) Send(m *AnswerResponse) error {
	return x.ClientStream.SendMsg(m)
}

func (x *signalingServiceAnswerClient) Recv() (*AnswerRequest, error) {
	m := new(AnswerRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *signalingServiceClient) OptionalWebRTCConfig(ctx context.Context, in *OptionalWebRTCConfigRequest, opts ...grpc.CallOption) (*OptionalWebRTCConfigResponse, error) {
	out := new(OptionalWebRTCConfigResponse)
	err := c.cc.Invoke(ctx, "/proto.rpc.webrtc.v1.SignalingService/OptionalWebRTCConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SignalingServiceServer is the server API for SignalingService service.
// All implementations must embed UnimplementedSignalingServiceServer
// for forward compatibility
type SignalingServiceServer interface {
	// Call makes an offer to a client that it expects an answer to. The host
	// of the client in question should be identified in the rpc-host metadata
	// field.
	// Note: Based on how this is a server streaming responnse to the caller,
	// we do not have a good way of knowing if the caller has disappeared.
	// Depending on answerer timeouts and concurrency limits, this can result in
	// hangs on the answerer waiting for a connection to establish, which in turn
	// can result in the caller waiting for an answerer to be listening.
	Call(*CallRequest, SignalingService_CallServer) error
	// CallUpdate is used to send additional info in relation to a Call.
	// The host of the client for the call in question should be identified
	// in the rpc-host metadata field.
	// In a world where https://github.com/grpc/grpc-web/issues/24 is fixed,
	// this should be removed in favor of a bidirectional stream on Call.
	CallUpdate(context.Context, *CallUpdateRequest) (*CallUpdateResponse, error)
	// Answer sets up an answering service where the caller answers call offers
	// and responds with answers.
	// The host(s) to answer for should be in the rpc-host metadata field.
	Answer(SignalingService_AnswerServer) error
	// OptionalWebRTCConfig returns any WebRTC configuration the caller may want to use.
	// The host to get a config for must be in the rpc-host metadata field.
	OptionalWebRTCConfig(context.Context, *OptionalWebRTCConfigRequest) (*OptionalWebRTCConfigResponse, error)
	mustEmbedUnimplementedSignalingServiceServer()
}

// UnimplementedSignalingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSignalingServiceServer struct {
}

func (UnimplementedSignalingServiceServer) Call(*CallRequest, SignalingService_CallServer) error {
	return status.Errorf(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedSignalingServiceServer) CallUpdate(context.Context, *CallUpdateRequest) (*CallUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallUpdate not implemented")
}
func (UnimplementedSignalingServiceServer) Answer(SignalingService_AnswerServer) error {
	return status.Errorf(codes.Unimplemented, "method Answer not implemented")
}
func (UnimplementedSignalingServiceServer) OptionalWebRTCConfig(context.Context, *OptionalWebRTCConfigRequest) (*OptionalWebRTCConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptionalWebRTCConfig not implemented")
}
func (UnimplementedSignalingServiceServer) mustEmbedUnimplementedSignalingServiceServer() {}

// UnsafeSignalingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SignalingServiceServer will
// result in compilation errors.
type UnsafeSignalingServiceServer interface {
	mustEmbedUnimplementedSignalingServiceServer()
}

func RegisterSignalingServiceServer(s grpc.ServiceRegistrar, srv SignalingServiceServer) {
	s.RegisterService(&SignalingService_ServiceDesc, srv)
}

func _SignalingService_Call_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CallRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SignalingServiceServer).Call(m, &signalingServiceCallServer{stream})
}

type SignalingService_CallServer interface {
	Send(*CallResponse) error
	grpc.ServerStream
}

type signalingServiceCallServer struct {
	grpc.ServerStream
}

func (x *signalingServiceCallServer) Send(m *CallResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SignalingService_CallUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServiceServer).CallUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.rpc.webrtc.v1.SignalingService/CallUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServiceServer).CallUpdate(ctx, req.(*CallUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SignalingService_Answer_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SignalingServiceServer).Answer(&signalingServiceAnswerServer{stream})
}

type SignalingService_AnswerServer interface {
	Send(*AnswerRequest) error
	Recv() (*AnswerResponse, error)
	grpc.ServerStream
}

type signalingServiceAnswerServer struct {
	grpc.ServerStream
}

func (x *signalingServiceAnswerServer) Send(m *AnswerRequest) error {
	return x.ServerStream.SendMsg(m)
}

func (x *signalingServiceAnswerServer) Recv() (*AnswerResponse, error) {
	m := new(AnswerResponse)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SignalingService_OptionalWebRTCConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptionalWebRTCConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SignalingServiceServer).OptionalWebRTCConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.rpc.webrtc.v1.SignalingService/OptionalWebRTCConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SignalingServiceServer).OptionalWebRTCConfig(ctx, req.(*OptionalWebRTCConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SignalingService_ServiceDesc is the grpc.ServiceDesc for SignalingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SignalingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.rpc.webrtc.v1.SignalingService",
	HandlerType: (*SignalingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallUpdate",
			Handler:    _SignalingService_CallUpdate_Handler,
		},
		{
			MethodName: "OptionalWebRTCConfig",
			Handler:    _SignalingService_OptionalWebRTCConfig_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Call",
			Handler:       _SignalingService_Call_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Answer",
			Handler:       _SignalingService_Answer_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/rpc/webrtc/v1/signaling.proto",
}
