service:
  golangci-lint-version: 1.43.x
run:
  deadline: 600s
  skip-dirs:
    - genfiles$
    - gen$
    - vendor$
    - test$
  tests: true
linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - funlen
    - gocognit
    - godox
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - interfacer
    - ireturn
    - maligned
    - nestif
    - nlreturn
    - paralleltest
    - prealloc
    - scopelint
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  lll:
    line-length: 140
  unused:
  gosec:
    excludes:
      - G601
  gci:
    local-prefixes: go.viam.com/utils
issues:
  exclude:
    - composites
  exclude-rules:
    - path: _test\.go$|^tests/|^samples/
      linters:
        - errcheck
        - goconst
        - gosec
        - govet
        - noctx
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
