service:
  golangci-lint-version: 1.51.x
run:
  deadline: 900s
  modules-download-mode: readonly
  skip-dirs:
    - genfiles$
    - gen$
    - vendor$
    - test$
  tests: true
linters:
  enable-all: true
  disable:
    - asasalint
    - containedctx
    - cyclop
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - forcetypeassert
    - funlen
    - gocognit
    - godox
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - golint
    - gomnd
    - ifshort
    - importas
    - interfacebloat
    - interfacer
    - ireturn
    - maintidx
    - maligned
    - makezero
    - musttag
    - nestif
    - nlreturn
    - nosnakecase
    - nonamedreturns
    - nosprintfhostport
    - paralleltest
    - prealloc
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - thelper # false positives
    - varcheck
    - varnamelen
    - wrapcheck
    - wsl
linters-settings:
  errcheck:
    check-blank: true
  gci:
    sections:
      - standard
      - default
      - prefix(go.viam.com/utils)
  gofumpt:
    lang-version: "1.18"
    extra-rules: true
  gosec:
    excludes:
      - G601
  govet:
    enable-all: true
    disable:
      - atomicalign
      - fieldalignment
      - shadow
  lll:
    line-length: 140
  revive:
    disable:
    - package-comments
issues:
  exclude:
    - composites
  exclude-rules:
    - path: _test\.go$|^tests/|^samples/
      linters:
        - errcheck
        - contextcheck
        - exhaustive
        - forcetypeassert
        - goconst
        - gosec
        - govet
        - noctx
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
