name: License Finder

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
    branches: ['main']
  push:

jobs:
  license_finder:
    name: Audit 3rd-Party Licenses
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/viamrobotics/canon:amd64-cache
      options: --platform linux/amd64
    timeout-minutes: 30

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run license finder
        run: |
          sudo -u testbot bash -lc 'license_finder'
